# ==========================================
# CONFIGURACION DE POSTGRES Y JPA
# ==========================================

# Configuracion de la base de datos PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/sigep
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=postgres

# Configuracion de JPA/Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=create-drop
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true
spring.jpa.defer-datasource-initialization=true

# Configuracion de inicializacion de datos
spring.sql.init.mode=always
spring.sql.init.data-locations=classpath:data.sql

# Configuracion del servidor
server.port=8080

# Configuracion de validacion
spring.mvc.throw-exception-if-no-handler-found=true
spring.web.resources.add-mappings=false
